pypress/core/admin/views.py
from flask import Blueprint, render_template, url_for, redirect, abort, flash, request
from flask_login.utils import login_required, current_user
from sqlalchemy.exc import IntegrityError

from pypress.models import Post, db, User

admin_blueprint = Blueprint('admin', __name__, template_folder='templates', static_folder='static')


@admin_blueprint.get('/admin/')
@login_required
def admin():
    if current_user.role not in ['admin']:
        return abort(403)
    return render_template('admin_ui.html', page='admin', title='Dashboard', file='dashboard.html')


@admin_blueprint.get('/admin/posts/')
@login_required
def admin_posts():
    posts = []
    session = db.session()

    result = session.query(Post, User).join(User, Post.user_id == User.id).all()

    for r in result:
        post_data = {'post_id': r[0].id, 'title': r[0].title, 'author': r[1].name, 'status': r[0].status, 'slug': r[0].slug}
        posts.append(post_data)

    session.close()
    return render_template('admin_ui.html', page='posts', title='Posts', file='posts.html', post_data=posts)


@admin_blueprint.get('/admin/pages/')
@login_required
def admin_pages():
    return render_template('admin_ui.html', page='pages', title='Pages', file='pages.html')


@admin_blueprint.get('/admin/comments/')
@login_required
def admin_comments():
    return render_template('admin_ui.html', page='comments', title='Comments', file='comments.html')


@admin_blueprint.get('/admin/users/')
@login_required
def admin_users():
    return render_template('admin_ui.html', page='users', title='Users', file='users.html')


@admin_blueprint.get('/admin/settings/')
@login_required
def admin_settings():
    return render_template('admin_ui.html', page='settings', title='Settings', file='settings.html')


@admin_blueprint.get('/admin/posts/compose/')
@login_required
def post_compose():
    return render_template('admin_ui.html', page='compose', title='Create a new post', file='compose.html')


@admin_blueprint.post('/admin/posts/compose/')
@login_required
def post_compose_next():
    data = request.form

    post_content = data['editor1']
    title = data['title']
    meta_description = data['meta_description']
    slug = data['slug']
    tags = data['tags']
    category = data['category']
    no_index = 'off'

    try:
        no_index = data['no_index']
    except KeyError:
        pass

    try:
        post = Post(title, post_content, meta_description, slug, tags, category, no_index, current_user.id, 'Published')
        print(post.id)
        db.session.add(post)
        db.session.commit()
        return redirect(url_for('admin.admin_posts'))
    except IntegrityError:
        flash('error')

    return render_template('admin_ui.html', page='compose', title='Create a new post', file='compose.html')

pypress/core/users/views.py
from flask import Blueprint, render_template, request, url_for, redirect, flash, abort, Markup
from flask_login import login_required, login_user, logout_user, current_user
from sqlalchemy import exc
from sqlalchemy.exc import IntegrityError
from werkzeug.security import generate_password_hash, check_password_hash, gen_salt
from pypress.models import User, db
import time

users = Blueprint('users', __name__, template_folder='templates')


@users.get('/admin/register/')
@login_required
def admin_register():
    return render_template('admin_auth_signup.html')


@users.post('/admin/register/')
@login_required
def admin_register_next():
    if current_user.role not in ['admin'] and current_user.authenticate == False: redirect(url_for('index'))
    data = request.form

    email = data['email']
    password = data['password']
    password_confirmation = data['passwordc']
    name = data['name']
    role = data['role']

    user = User.query.filter_by(email=email).first()

    if user is None and password == password_confirmation:
        print(data)
        try:
            password = generate_password_hash(password)

            new_user = User(email, name, password, role, gen_salt(16), time.time())
            new_user.authenticated = True
            db.session.add(new_user)
            db.session.commit()
            message = Markup(
                "<strong>Success!</strong> Thanks for registering. Please check your email to confirm your email address.")
            flash(message, 'success')
            return redirect(url_for('users.login', success="true"))
        except IntegrityError:
            print('integrity error')
            db.session.rollback()
            message = Markup(
                "<strong>Error!</strong> Unable to process registration.")
            flash(message, 'danger')

    return render_template('admin_auth_signup.html')


@users.get('/login/')
def login():
    return render_template('admin_auth.html')


@users.post('/login/')
def login_next():
    data = request.form

    email = data['email']
    password = data['password']

    user = User.query.filter_by(email=email).first()

    if email == user.email and check_password_hash(user.password, password):
        print("Verified user")
        login_user(user, remember=True)

        next = request.args.get('next')

        return redirect(next or url_for('index'))

    return render_template('admin_auth.html')


@users.get('/logout/')
def logout():
    logout_user()
    next = request.args.get('next')
    return redirect(url_for(next or 'index'))

pypress/templates/admin_auth.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>pypress admin login</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/sign-in/">

    

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj"
    crossorigin="anonymous"></script>
    <link href="{{ url_for('static', filename='css/auth.css')}}" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="signin.css" rel="stylesheet">
  </head>
  <body class="text-center">
    
<main class="form-signin">
  <form method="POST" action="">
    
    <h1 class="h3 mb-3 fw-normal">pypress</h1>

    <div class="form-floating">
      <input type="email" class="form-control" id="floatingInput" name="email" placeholder="name@example.com">
      <label for="floatingInput">Email address</label>
    </div>
    <div class="form-floating">
      <input type="password" class="form-control" id="floatingPassword" name="password" placeholder="Password">
      <label for="floatingPassword">Password</label>
    </div>

    <div class="checkbox mb-3">
      <label>
        <input type="checkbox" value="remember-me"> Remember me
      </label>
    </div>
    <button class="w-100 btn btn-lg btn-primary" type="submit">Sign in</button>
    <p>
      
        {% if request.args.get('success') == 'true'  %}
          "Account created. Please sign-in"
        {% endif %}

    </p>
  </form>
</main>


    
  </body>
</html>

pypress/templates/admin_auth_signup.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>pypress admin login</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/sign-in/">


    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj"
            crossorigin="anonymous"></script>
    <link href="{{ url_for('static', filename='css/auth.css') }}" rel="stylesheet">

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>


    <!-- Custom styles for this template -->
    <link href="signin.css" rel="stylesheet">
</head>
<body class="text-center">

<main class="form-signin">
    <form method="POST" action=''>

        <h1 class="h3 mb-3 fw-normal">pypress</h1>

        <div class="form-floating">
            <input type="email" class="form-control" id="floatingInput" name="email" placeholder="name@example.com"
                   required>
            <label for="floatingInput">Email address</label>
        </div>

        <div class="form-floating">
            <input type="text" class="form-control" id="floatingInput2" name="name" placeholder="Name" required>
            <label for="floatingInput2">Name</label>
        </div>
        <div class="form-floating">
            <input type="password" class="form-control" id="floatingPassword" name="password" placeholder="Password"
                   required>
            <label for="floatingPassword">Password</label>
        </div>
        <div class="form-floating">
            <input type="password" class="form-control" id="floatingPassword2" name="passwordc"
                   placeholder="Confirm Password" required>
            <label for="floatingPassword2">Confirm Password</label>
        </div>
        <div class="mb-3">

            <select class="form-select" id="role", name="role" aria-label="Select role">
                <option selected>Select role</option>
                <option value="admin">Admin</option>
                <option value="author">Author</option>
              </select>
        </div>
        {% if success == False %}
            <p>{{ err }}</p>
        {% endif %}
        <button class="w-100 btn btn-lg btn-primary" type="submit">Create account</button>
    </form>
</main>


</body>
</html>

pypress/templates/admin_ui.html
{% set active_page = page %}
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
  <meta name="generator" content="Hugo 0.87.0">
  <title>{{ title }} - pypress</title>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj"
    crossorigin="anonymous"></script>



  <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
  </style>


  <!-- Custom styles for this template -->
  <link href="{{ url_for('static', filename='css/dashboard.css')}}" rel="stylesheet">
</head>

<body>

  <header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-md-3 col-lg-2 me-0 px-4" href="#"><span data-feather="edit-2"></span> pypress</a>
    <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse"
      data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-nav">
      <div class="nav-item text-nowrap">
        <a class="nav-link px-3" href="{{ url_for('users.logout')}}">Sign out, 
          {% if current_user.is_authenticated and current_user.role == 'admin' %}
              Hi {{ current_user.name }}
          {% endif %}
        </a>
      </div>
    </div>
  </header>

  <div class="container-fluid">
    <div class="row">
      {% include 'menu.html' %}


      {% include file %}

    </div>
  </div>




  <script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js"
    integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js"
    integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha"
    crossorigin="anonymous"></script>
  <script src="{{url_for('static', filename='js/dashboard.js')}}"></script>
</body>

</html>

pypress/templates/comments.html
<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">{{ title }}</h1>
        <div class="btn-toolbar mb-2 mb-md-0">

            <button type="button" class="btn btn-sm btn-outline-secondary">
                <span data-feather="plus"></span>
                Create new post
            </button>
            <button type="button" class="btn btn-sm btn-outline-secondary">
                <span data-feather="file"></span>
                Manage categories
            </button>

            <button type="button" class="btn btn-sm btn-outline-secondary">
                <span data-feather="hash"></span>
                Manage tags
            </button>
        </div>
    </div>


    <h6>Section</h6>
</main>

pypress/templates/compose.html
<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">{{ title }}</h1>
        <div class="btn-toolbar mb-2 mb-md-0">




            &nbsp;
            <a type="button" class="btn btn-sm btn-outline-secondary" href=#>
                <span data-feather="paperclip"></span>
                Save as draft
            </a>
            &nbsp;
            <buttontype="button" class="btn btn-sm btn-outline-secondary" onclick="document.querySelector('#post').submit()">
                <span data-feather="send"></span>
                Publish
        </button>
        </div>

    </div>

    <form style="margin-top: 20px;", id='post' method="POST" action="">
    
        <textarea name="editor1" id="editor1" rows="500" cols="80" name="content">
        </textarea>


    
        <h6 style="margin-top: 20px;">Metadata & SEO</h6>
{#        <div class="mb-3">
            <label for="permalink" class="form-label">Permalink</label>
            <input type="text" class="form-control" id="permalink" aria-describedby="permalinkHelp" name="permalink" disabled>
            <div id="permalinkHelp" class="form-text">This is how the URL will look like once you publish your post</div>
        </div>#}
        <div class="mb-3">
          <label for="title" class="form-label">Title</label>
          <input type="text" class="form-control" id="title" aria-describedby="titleHelp" name="title" oninput="fillSlugHook()">
          <div id="titleHelp" class="form-text">Title of your post</div>
        </div>
        <div class="mb-3">
            <label for="meta_description" class="form-label">Meta Description</label>
            <input type="text" class="form-control" id="meta_description" aria-describedby="metaHelp" name="meta_description">
            <div id="metaHelp" class="form-text">This is what will show up on Google and other search engines</div>
        </div>
        <div class="mb-3">
          <label for="slug" class="form-label">Slug</label>
          <input type="text" class="form-control" id="slug" aria-describedby="slugHelp" name="slug">
          <div id="slugHelp" class="form-text">Customize your URL slug</div>
        </div>


        <div class="mb-3">
          <label for="tags" class="form-label">Tags</label>
          <input type="text" class="form-control" id="tags" aria-describedby="tagsHelp" name="tags">
          <div id="tagsHelp" class="form-text">Set a tag for your post (seperate multiple items with a commna).</div>
        </div>

        <div class="mb-3">
            <label for="category" class="form-label">Category</label>
            <select class="form-select" id="category", name="category" aria-label="Default select example">
                <option selected>Select a category</option>
                <option value="1">One</option>
                <option value="2">Two</option>
                <option value="3">Three</option>
              </select>
        </div>
        <div class="mb-3 form-check">
          <input type="checkbox" class="form-check-input" id="noindex" name="noindex" aria-describedby="noindexHelp">
          <label class="form-check-label" for="noindex">no-index</label>
          <div id="noindexHelp" class="form-text">Exclude this post from search engine results</div>
        </div>
      </form>

</main>

<script src="https://cdn.ckeditor.com/4.16.1/full-all/ckeditor.js"></script>

<script>
    // Replace the <textarea id="editor1"> with a CKEditor 4
    // instance, using default configuration.
    CKEDITOR.replace( 'editor1' );
</script>

pypress/templates/dashboard.html
<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">{{ title }}</h1>
        <div class="btn-toolbar mb-2 mb-md-0">

            <button type="button" class="btn btn-sm btn-outline-secondary">
                <span data-feather="plus"></span>
                Create new post
            </button>
            <button type="button" class="btn btn-sm btn-outline-secondary">
                <span data-feather="file"></span>
                Manage categories
            </button>

            <button type="button" class="btn btn-sm btn-outline-secondary">
                <span data-feather="hash"></span>
                Manage tags
            </button>
        </div>
    </div>


    <h6>Section</h6>
</main>

pypress/templates/index.html
{% if current_user.is_authenticated %}
  Hi {{ current_user.name }}! {{ current_user.id }} {{ current_user.salt }}
{% endif %}

pypress/templates/menu.html
<nav id="sidebarMenu" class="col-md-2 col-lg-2 d-md-block bg-light sidebar collapse">
    <div class="position-sticky pt-3">
      <ul class="nav flex-column">
        <li class="nav-item">
          <a class="nav-link {{ 'active' if active_page == 'admin' else '' }}" aria-current="page" href="{{ url_for('admin.admin')}}">
            <span data-feather="home"></span>
            Dashboard
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link {{ 'active' if active_page == 'posts' else '' }}" href="{{ url_for('admin.admin_posts')}}">
            <span data-feather="edit"></span>
            Posts
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link {{ 'active' if active_page == 'pages' else '' }}" href="{{ url_for('admin.admin_pages')}}">
            <span data-feather="file"></span>
            Pages
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link {{ 'active' if active_page == 'comments' else '' }}" href="{{ url_for('admin.admin_comments')}}">
            <span data-feather="message-square"></span>
            Comments
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link {{ 'active' if active_page == 'users' else '' }}" href="{{ url_for('admin.admin_users')}}">
            <span data-feather="users"></span>
            Users
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link {{ 'active' if active_page == 'settings' else '' }}" href="{{ url_for('admin.admin_settings')}}">
            <span data-feather="settings"></span>
            Settings
          </a>
        </li>
      </ul>


    </div>
  </nav>

pypress/templates/pages.html
<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">{{ title }}</h1>
        <div class="btn-toolbar mb-2 mb-md-0">

            <a type="button" class="btn btn-sm btn-outline-secondary" href="#">
                <span data-feather="plus"></span>
                Create new page
            </a>
        </div>
    </div>


    <h6>Section</h6>
</main>

pypress/templates/posts.html
<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
    <div
            class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">{{ title }}</h1>
        <div class="btn-toolbar mb-2 mb-md-0">

            <a type="button" class="btn btn-sm btn-outline-secondary" href="{{ url_for('admin.post_compose') }}">
                <span data-feather="plus"></span>
                Create new post
            </a>
            &nbsp;
            <a type="button" class="btn btn-sm btn-outline-secondary">
                <span data-feather="file"></span>
                Manage categories
            </a>
        </div>
    </div>


    <table class="table">
        <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Title</th>
            <th scope="col">Status</th>
            <th scope="col">Author</th>
            <th scope="col"></th>
        </tr>
        </thead>
        <tbody>

        {% for p in post_data %}
            <tr>
                <td>{{ p['post_id'] }}</td>
                <td>{{ p['title'] }}</td>
                <td>{{ p['status'] }}</td>
                <td>{{ p['author'] }}</td>
                <td><a href="">Edit</a>&nbsp; <a href="/posts/{{ p['slug'] }}">View</a></td>

            </tr>
            <p></p>
        {% endfor %}

        </tbody>
    </table>
</main>

pypress/templates/settings.html
<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">{{ title }}</h1>
        <div class="btn-toolbar mb-2 mb-md-0">

            <button type="button" class="btn btn-sm btn-outline-secondary">
                <span data-feather="plus"></span>
                Create new post
            </button>
            <button type="button" class="btn btn-sm btn-outline-secondary">
                <span data-feather="file"></span>
                Manage categories
            </button>

            <button type="button" class="btn btn-sm btn-outline-secondary">
                <span data-feather="hash"></span>
                Manage tags
            </button>
        </div>
    </div>


    <h6>Section</h6>
</main>

pypress/templates/users.html
<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">{{ title }}</h1>
        <div class="btn-toolbar mb-2 mb-md-0">

            <a type="button" class="btn btn-sm btn-outline-secondary" href="{{ url_for('users.admin_register') }}">
                <span data-feather="plus"></span>
                New user
            </a>


        </div>
    </div>

    <table class="table">
        <thead>
          <tr>
            <th scope="col">ID</th>
            <th scope="col">Name</th>
            <th scope="col">Email</th>
            <th scope="col">Role</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th scope="row">1</th>
            <td>Jacob Hernandez</td>
            <td>hakube@outlook.com</td>
            <td>Superadmin</td>
            <td><a href="">Edit</a>&nbsp; <a href="http://">View</a></td>
          </tr>
          <tr>
            <th scope="row">2</th>
            <td>Nate Miller</td>
            <td>nate@pypress-cms.org</td>
            <td>Admin</td>
            <td><a href="">Edit</a>&nbsp; <a href="http://">View</a></td>
          </tr>
          <tr>
            <th scope="row">3</th>
            <td>Larry the Bird</td>
            <td>larry@bird.org</td>
            <td>Author</td>
            <td><a href="">Edit</a>&nbsp; <a href="http://">View</a></td>
          </tr>
        </tbody>
      </table>


    
</main>